name: eden_autosklearn
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - scikit-learn=0.24.1  
  - numpy=1.20.2
  - opencv=3.4
  - tqdm=4.59.0
  - matplotlib=3.3
  - pip=21.0.1
  - pip:
     - auto-sklearn 0.12