name: eden_autokeras
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - numpy=1.20.2
  - scikit-learn=0.24.1  
  - tensorflow=2.3
  - opencv=3.4
  - tqdm=4.59.0
  - matplotlib=3.3
  - pandas=0.25
  - pip=21.0.1
  - pip:
      - autokeras
    